### ISSUE TITLE
Improved Span Search

### ISSUE THREAD

**Issue by davit-y** [jaegertracing/jaeger-ui#235]
This is a centralized issue for all the PRs related to improving span search on the trace page.

## PRs
- [ ] #234  Initial UI Improvements (navigation and clear buttons, result count, shortcuts)
- [ ] #237 Search query improvements (search by tags, processes, log, and ignore keys)
- [ ] #238 Improve result highlighting

**Comment by tiffon** [comment]
Ran across an interesting way of demarcating matches where the match is currently hidden due to collapsing. 

<img width="768" alt="__the-matching-is-nice" src="https://user-images.githubusercontent.com/2304337/44124335-ba522274-9ffa-11e8-9a74-49eca551cd72.png">

**Comment by tiffon** [comment]
Closing, as the PRs called out (#234, #237, #238) are already merged.
